# Generated by Django 4.2.7 on 2024-01-13 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests_taken', models.PositiveIntegerField(default=0)),
                ('total_tokens_received', models.PositiveIntegerField(default=0)),
                ('current_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_current_lesson', to='levels.lesson')),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_current_level', to='levels.level')),
                ('lessons_completed', models.ManyToManyField(blank=True, related_name='progress_lessons_completed', to='levels.lesson')),
                ('levels_completed', models.ManyToManyField(blank=True, related_name='progress_levels_completed', to='levels.level')),
                ('sublevels_completed', models.ManyToManyField(blank=True, related_name='progress_sublevels_completed', to='levels.sublevel')),
                ('test_results', models.ManyToManyField(blank=True, related_name='progress_test_results', to='levels.testresult')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
